Check Hoax_Valid

In [20]:
import pandas as pd
df_raw = pd.read_csv("dataset/hoax_valid.csv")

df_raw.head(10)

                                              berita label
0  Foto Putra Panglima Militer Israel yang Cacat ...  hoax
1  Gibran Membagikan Rp 20 Juta di TikTok KOMPAS....  hoax
2  Video Mamah Dedeh Janjikan Bantuan Rp 35 Juta ...  hoax
3  Bantuan Dana Rp 2,5 Juta untuk Pemegang KIS KO...  hoax
4  WHO Akui Mpox adalah Efek Samping Covid-19 KOM...  hoax
5  Raffi Ahmad Bagikan Rp 200 Juta Melalui Akun I...  hoax
6  Imbauan Mematikan Ponsel untuk Hindari Radiasi...  hoax
7  Surat Pemberitahuan Perubahan Biaya Transfer B...  hoax
8  Ada Tulisan "Vinicius Junior" di Trofi Ballon ...  hoax
9  Lagu "Indonesia Raya" Digunakan untuk Pembukaa...  hoax

In [21]:

df = pd.read_csv("dataset/hoax_valid_labeled.csv")

df.head(10)

                                              berita  label
0  Foto Putra Panglima Militer Israel yang Cacat ...      1
1  Gibran Membagikan Rp 20 Juta di TikTok KOMPAS....      1
2  Video Mamah Dedeh Janjikan Bantuan Rp 35 Juta ...      1
3  Bantuan Dana Rp 2,5 Juta untuk Pemegang KIS KO...      1
4  WHO Akui Mpox adalah Efek Samping Covid-19 KOM...      1
5  Raffi Ahmad Bagikan Rp 200 Juta Melalui Akun I...      1
6  Imbauan Mematikan Ponsel untuk Hindari Radiasi...      1
7  Surat Pemberitahuan Perubahan Biaya Transfer B...      1
8  Ada Tulisan "Vinicius Junior" di Trofi Ballon ...      1
9  Lagu "Indonesia Raya" Digunakan untuk Pembukaa...      1

In [22]:
print(f"The dataset contains {df.shape[0]} transactions and each transaction has a maximum of {df.shape[1]} items or less.")
df.tail(10)

The dataset contains 5258 transactions and each transaction has a maximum of 2 items or less.

                                                 berita  label
5248  3 Fakta Madrid Vs Milan: Malam Kelam Los Blanc...      0
5249  Kronologi Anak di Cirebon Nekat Bakar Rumah Or...      0
5250  Duduk Perkara Beda Hasil Survei Pilkada Jakart...      0
5251  Mendikti: Alumni LPDP di Luar Negeri Tak Harus...      0
5252  Cara Mudah Ganti Data MyPertamina Dapatkan QR ...      0
5253  Status Gunung Iya Ende Naik ke Level Siaga END...      0
5254  Prabowo Akan Hadiri Undangan Xi Jinping ke Chi...      0
5255  Jika Nilai SKD CPNS 2024 Sama dengan Peserta L...      0
5256  Lokasi SIM Keliling di Jakarta Hari Ini 6 Nove...      0
5257  Polisi Kok Emosi... JAKARTA, KOMPAS.com &ndash...      0

HoaxValid_Clean

In [23]:
df_hoaxvalid = pd.read_csv("cleandataset/hoaxvalid_cleaned.csv")
df_hoaxvalid.head(10)

                                        cleaned_text  label
0  foto putra panglima militer israel cacat umur ...      1
1  gibran bagi rp juta tiktok kompascom edar vide...      1
2  video mamah dedeh janji bantu rp juta kompasco...      1
3  bantu dana rp juta pegang kis kompascom pegang...      1
4  who aku mpox efek samping covid kompascom edar...      1
5  raffi ahmad bagi rp juta akun instagram kompas...      1
6  imbau mati ponsel hindar radiasi kosmik kompas...      1
7  surat pemberitahuan ubah biaya transfer bank j...      1
8  tulis vinicius junior trofi ballon dor milik r...      1
9  lagu indonesia raya buka piala dunia kompascom...      1

In [24]:
print(f"The dataset contains {df_hoaxvalid.shape[0]} transactions and each transaction has a maximum of {df_hoaxvalid.shape[1]} items or less.")
df_hoaxvalid.tail(10)

The dataset contains 5258 transactions and each transaction has a maximum of 2 items or less.

                                           cleaned_text  label
5248  fakta madrid vs mil malam kelam los blancos be...      0
5249  kronologi anak cirebon nekat bakar rumah orang...      0
5250  duduk perkara beda hasil survei pilkada jakart...      0
5251  mendikti alumni lpdp negeri pulang indonesia k...      0
5252  mudah ganti data mypertamina dapat qr code bel...      0
5253  status gunung iya ende level siaga ende kompas...      0
5254  prabowo hadir undang xi jinping china november...      0
5255  nilai skd cpns serta tentu kompascom proses se...      0
5256  lokasi sim keliling jakarta november kompascom...      0
5257  polisi emosi jakarta kompascom ndash jadi poli...      0

Check Politik

In [25]:
df_rawpolitik = pd.read_csv("dataset/politik.csv")
df_rawpolitik.head(10)

,ID,tanggal,judul,narasi,nama file gambar,text,label
0,238057,13-Jul-20,narasi tito karnavian berideologi komunis dise...,tito karnivan beridiologi komunis pki sekolahl...,238057.jpg,narasi tito karnavian berideologi komunis dise...,1
1,238158,6-Jul-20,anies seberat beratnya pekerjaan ringan kerjakan,seberat beratnya pekerjaan ringan kerjakan,238158.jpg,anies seberat beratnya pekerjaan ringan kerjak...,1
2,238865,22-Apr-20,hindu india melemparkan patung buatan laut men...,hindu india melemparkan patung buatan laut lak...,238865.jpg,hindu india melemparkan patung buatan laut men...,1
3,248298,22-Oct-19,rscm praktekkan penyedotan plug venasaluran darah,rscm dipraktekkan penyedotan plug sumbatan ven...,248298.jpg,rscm praktekkan penyedotan plug venasaluran da...,1
4,255176,1-May-20,permohonan kelonggaran angsuran ojk,sekedar info yg ansurancicilan kelonggaran lea...,255176.jpg,permohonan kelonggaran angsuran ojk sekedar in...,1
5,267051,15-Sep-18,aksi bem sejabotabek,assalamua ’ laikum warahmatullahi wabarakatuh ...,267051.jpg,aksi bem sejabotabek assalamua ’ laikum warahm...,0
6,269336,18-Mar-17,sinar kosmik berbahaya radiasi,malam pastikan mematikan telepon tv singapura ...,269336.jpg,sinar kosmik berbahaya radiasi malam pastikan ...,1
7,272438,8-Jan-20,smkn klarifikasi perihal kabar viral pasang fo...,lokasi smkn jakarta utara sekolah negeri memas...,272438.jpg,smkn klarifikasi perihal kabar viral pasang fo...,0
8,282152,11-Apr-19,pembuatan ktp orang gila ambisi kekuasaan,parah…memaksakan wajar ambisi kekuasaan… pembu...,282152.jpg,pembuatan ktp orang gila ambisi kekuasaan para...,1
9,288490,12-Mar-20,daniel radcliffe positiv terinfeksi corona covid,breaking daniel radcliffe test posotive for co...,288490.jpg,daniel radcliffe positiv terinfeksi corona cov...,1

Politik Cleaned

In [26]:
df_politik = pd.read_csv("cleandataset/politik_cleaned.csv")
df_politik.head(10)

                                        cleaned_text  label
0  narasi tito karnavian ideologi komunis sekolah...      1
1  anies berat berat kerja ringan kerja berat ber...      1
2  hindu india lempar patung buat laut tolong cor...      1
3  rscm praktek sedot plug venasaluran darah rscm...      1
4  mohon longgar angsur ojk dar info yg ansuranci...      1
5  aksi bem sejabotabek assalamua  laikum warahma...      0
6  sinar kosmik bahaya radiasi malam pasti mati t...      1
7  smkn klarifikasi perihal kabar viral pasang fo...      0
8  buat ktp orang gila ambisi kuasa parah paksa w...      1
9  daniel radcliffe positiv infeksi corona covid ...      1

In [27]:
print(f"The dataset contains {df_politik.shape[0]} transactions and each transaction has a maximum of {df_politik.shape[1]} items or less.")
df_politik.tail(10)

The dataset contains 470 transactions and each transaction has a maximum of 2 items or less.

                                          cleaned_text  label
460  sptmau ngemis suara muslimgak malu spt mau nge...      1
461  foto massa tumpah ruah kepung gedung dpr kait ...      1
462  racun nasi magic com keluar nasi rice cooker s...      1
463  lindung saudara muslim rohingya muslim dunia i...      1
464  foto serta video pesawat tempur rudal israel a...      0
465  jemput tim medis kakak adik usia tangerang jan...      1
466  tanda alam kera putih turun gunung agung tanda...      0
467  pasar wameo karya nugraha tutup minggu assalam...      1
468  klarifikasi kpk kait foto setya novanto baju t...      0
469  erdogan aku menang jokowi artikel laman daring...      1

Check Combine

In [28]:
import pandas as pd

In [29]:
df_final = pd.read_csv("cleandataset/hoax_dataset_merged_v2.csv")
df_final.head(10)

                                             cleaned  label
0  kota dunia rawan risiko lancong saran asuransi...      0
1  rasa fitur corolla cross hybrid gr sport lengk...      0
2  hasil man united vs paok gol diallo hadir poin...      0
3  temu prabowo menkes lapor potensi kerja asingg...      0
4  ras kucing bulu tebal jakarta kompascom salah ...      0
5  mantan gubernur jawa barat danny setiawan ting...      1
6  nasionalisme indonesia raya kumandang gedung d...      0
7  cipta aman rumah sandang disabilitas tim robot...      0
8  masuk musim hujan desa ponorogo krisis air ber...      0
9  foto post presiden chechnya dukung prabowo san...      1

In [30]:
print(f"The dataset contains {df_final.shape[0]} transactions and each transaction has a maximum of {df_final.shape[1]} items or less.")
df_final.tail(10)

The dataset contains 33186 transactions and each transaction has a maximum of 2 items or less.

                                                 cleaned  label
33176  jakarta komisi vi dpr sorot pinjam yang beri b...      1
33177  jakarta hanter rencana perintah yang ingin hap...      1
33178  jadi hok mending lo tidur aje ngga usah ngelua...      1
33179  pas kampanye ada warning duga pki bangkit di e...      1
33180  pada april lalu menteri dagang rachmat gobel l...      1
33181  raja salman dari arab saudi bawa orang orang y...      1
33182  hehe selalu bisa senyum lihat tingkah laku pak...      1
33183  pak jokowi itu jadi walikota periode pertama d...      1
33184  hari ini rabu nilai tukar rupiah puruk hingga ...      1
33185  mari kita tolak desember acara pastur di monas...      1

In [31]:
print(df_final.head())
print(df_final['label'].value_counts())

                                             cleaned  label
0  kota dunia rawan risiko lancong saran asuransi...      0
1  rasa fitur corolla cross hybrid gr sport lengk...      0
2  hasil man united vs paok gol diallo hadir poin...      0
3  temu prabowo menkes lapor potensi kerja asingg...      0
4  ras kucing bulu tebal jakarta kompascom salah ...      0
label
0    23680
1     9506
Name: count, dtype: int64

In [32]:
df_cnn = pd.read_excel("dataset/cnn.xlsx")
df_cnn.head(5)

,Unnamed: 0,Title,Timestamp,FullText,Tags,Author,Url,text_new,hoax
0,0,Anies di Milad BKMT: Pengajian Menghasilkan Ib...,"Selasa, 21 Feb 2023 21:22 WIB","Jakarta, CNN Indonesia -- Mantan Gubernur DKI ...",anies baswedan;pengajian;pilpres 2024;badan ko...,CNN Indonesia,https://www.cnnindonesia.com/nasional/20230221...,Anies di Milad BKMT: Pengajian Menghasilkan Ib...,0
1,1,Edy Soal Pilgub Sumut: Kalau yang Maju Abal-ab...,"Selasa, 21 Feb 2023 20:46 WIB","Medan, CNN Indonesia -- Gubernur Sumatera Utar...",edy rahmayadi;pemilu 2024;pilkada 2024,CNN Indonesia,https://www.cnnindonesia.com/nasional/20230221...,Edy Soal Pilgub Sumut: Kalau yang Maju Abal-ab...,0
2,2,PKB Bakal Daftarkan Menaker Ida Fauziyah Jadi ...,"Selasa, 21 Feb 2023 20:33 WIB","Jakarta, CNN Indonesia -- Partai Kebangkitan B...",ida fauziyah;pkb;pemilu 2024;pileg 2024,CNN Indonesia,https://www.cnnindonesia.com/nasional/20230221...,PKB Bakal Daftarkan Menaker Ida Fauziyah Jadi ...,0
3,3,Gede Pasek Doakan AHY Jadi Capres atau Cawapres,"Selasa, 21 Feb 2023 19:58 WIB","Jakarta, CNN Indonesia -- Ketua Umum Partai Ke...",gede pasek suardika;ahy;pilpres 2024;pemilu 20...,CNN Indonesia,https://www.cnnindonesia.com/nasional/20230221...,Gede Pasek Doakan AHY Jadi Capres atau Cawapre...,0
4,4,PKN Siapkan Jabatan Khusus Buat Anas Urbaningr...,"Selasa, 21 Feb 2023 18:56 WIB","Jakarta, CNN Indonesia -- Dewan Pimpinan Pusat...",anas urbaningrum;pkn;pemilu 2024,CNN Indonesia,https://www.cnnindonesia.com/nasional/20230221...,PKN Siapkan Jabatan Khusus Buat Anas Urbaningr...,0